# edit the following title and description to match your suite repository
title: "Tool Suite Template"
description: "Repository template to create a tools suite for the Rusty Data Interface (RuDI)"

# edit the following for the upper-right navigation link on the documentation page
aux_links:
  "Go To Repo on GitHub":
    - "https://github.com/RustyDataInt/rudi-suite-template"

# OPTIONAL: uncomment to list any external tool suite dependencies
# suite_dependencies:
#   - GIT_USER/REPOSITORY_NAME

# OPTIONAL: declare support for suite-level singularity containers
container:
  supported:  false    # set to true if you maintain a suite-level container registry for this repository
  registry:   ghcr.io  # domain name of your OCI-compatible, oras-accessible, container registry
  owner:      GIT_USER # REQUIRED: the name of the owner, e.g., user or organization, at 'registry'
  installer:  apt-get  # the installer program used by the container OS, typically apt-get or yum
  stages:
    pipelines: false   # set to true to install conda environments into a suite-level pipelines container
    apps:      false   # set to true to install conda environments into a suite-level apps container
                       # one of stages:pipelines or stages:apps must be true if container:supported is true
                       # alternatively, support pipeline-level containers by the 'container' key in pipeline.yml

#------------------------------------------------------------------------------
# please do not edit any lines below this line
#------------------------------------------------------------------------------

# theme information
remote_theme: RustyDataInt/just-the-docs-rudi
logo: "/assets/images/rudi-logo-text-200.png"

# footer content
back_to_top: true
back_to_top_text: "Top of page"
footer_content: " "

# web tracking
# ga_tracking: UA-1234567-89 # Google Analytics
plugins:
  - jekyll-seo-tag

# page defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: docs
    values:
      layout: "default"
