#!/bin/sh

#--------------------------------------------------------------------
# the 'run' script supports direct calls to a RuDI tools suite
# it is a surrogate to the 'rudi' utility specific to this suite installation
#--------------------------------------------------------------------
# this script can be renamed to anything you'd like, e.g., a short suite name
#--------------------------------------------------------------------
IS_MULTI_SUITE="is-multi-suite"
IS_SINGLE_SUITE="is-single-suite"

#----------------------------------------------------------------------
# base directory of this tool suite, after user cloned it from GitHub
#----------------------------------------------------------------------
export SUITE_DIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd)"
export SUITE_NAME="$(basename "$SUITE_DIR")"
export SUITE_TARGET_NAME="$(basename "$0")"

#----------------------------------------------------------------------
# discover whether this suite is in a is-multi-suite or is-single-suite installation
# if it is contained in a parent rudi/suites/* folder, then it is always is-multi-suite
#----------------------------------------------------------------------
export SUITE_MODE="$IS_MULTI_SUITE"
export RUDI_DIR="$SUITE_DIR/../../.."
export RUDI_TARGET="$RUDI_DIR/rudi"
if [ ! -d "$RUDI_DIR/frameworks" ] || [ ! -d "$RUDI_DIR/suites" ] || [ ! -f "$RUDI_TARGET" ]; then
    export SUITE_MODE="$IS_SINGLE_SUITE" # i.e., this is the top-level of a single-suite installation
    export RUDI_DIR="$SUITE_DIR/rudi"
    export RUDI_TARGET="$RUDI_DIR/rudi"
fi
IS_READLINK="$(which readlink 2>/dev/null)"
if [ -n "$IS_READLINK" ]; then 
    export RUDI_DIR="$(readlink -f "$RUDI_DIR")"
fi

#----------------------------------------------------------------------
# if is-multi-suite, exit with a helpful message and no action taken
#----------------------------------------------------------------------
if [ "$SUITE_MODE" = "$IS_MULTI_SUITE" ]; then
    printf "\nNothing to do.\n\n"
    printf "This copy of '%s' is part of a RuDI installation in directory:\n    %s\n\n" "$SUITE_NAME" "$RUDI_DIR"
    printf "Use it by calling the 'rudi' command line utility in that directory (multi-suite installation)\n"
    printf "or the 'run' script in the parent of that directory (single suite installation).\n\n"
    exit 1
fi

#----------------------------------------------------------------------
# if is-single-suite, ensure that the framework was previously installed
#----------------------------------------------------------------------
if [ ! -f "$RUDI_TARGET" ]; then
    printf "\nPlease install '%s' first using command './install.sh'.\n\n" "$SUITE_NAME"
    exit 1
fi

#----------------------------------------------------------------------
# pass the call to the nested RuDI installation, providing customization metadata
#----------------------------------------------------------------------   
export JOB_MANAGER_NAME_FULL="$SUITE_NAME:$SUITE_TARGET_NAME"
export JOB_MANAGER_NAME="$SUITE_TARGET_NAME"
exec "$RUDI_TARGET" "$@"
