# Configuration file for values that apply to one app.

# App metadata.
order = 1 # for sorting apps in the app chooser
name = "demo_app"  # must match Cargo.toml in this same app folder; no spaces
label = "Demo App" # for display in the UI
description = "A simple demonstration of how to build a RuDI app."

# Data package types, as defined by pipelines, that the app can take as input.
# Add additional supported data package types as needed.
[package_types]
demo_data = [ "demo_csv" ] # array elements list required content file types

# App steps listed on the left sidebar tab navigator, in this order.
# Add additional app steps as needed.
[[app_steps]]
name = "user_inputs"               # required: no spaces
label = "User Inputs"         # required: for display in the UI side navbar
component = "UserInputs"      # required: the Dioxus component function, re-exported in the app's lib.rs
title = "User input examples" # required: shown at the top of the app step page
tooltip = "Demonstration of various stateful user inputs" # optional: defaults to title if not provided
# in addition, each app step can provide:
#      instructions as <app_name>/src/<app_step_name>/instructions.md
#      settings     as <app_name>/src/<app_step_name>/settings.yml

[[app_steps]]
name = "page_layout"
label = "Page Layout"
component = "PageLayout"
title = "Bootstrap-style page layout"
tooltip = "Description of the 12-column page layout used in app steps"

[[app_steps]]
name = "data_tables"
label = "Data Tables"
component = "DataTables"
title = "Interactive data tables"
tooltip = "Demonstration of interactive data table panels"

[[app_steps]]
name = "data_plots"
label = "Data Plots"
component = "DataPlots"
title = "Interactive data plots"
tooltip = "Demonstration of interactive data plot panels"
