//! The `main.rs` file in the `server` crates is the entry point 
//! for the server application that runs your apps.
//! 
//! Do not edit this file.  All code it needs is either:
//!   - built by `server::build.rs` via `rudi::server::build()`
//!   - called by the built code from `rudi::server` and other modules

// Include the generated server code, which includes
//   - required imports, including all apps with re-exported app step components
//   - the `RudiRouter` app step server routes enum 
//   - the assembled server configuration, accessed via `get_server_config()`
//   - the server and client `main()` functions for running the app
include!(concat!(env!("OUT_DIR"), "/generated_server_code.rs"));


// imports
use std::sync::OnceLock;
use dioxus::prelude::*;
use rudi::server::config::*;

// router enum here

/// Return a reference to the suite config, with all app configs.
pub fn get_server_config() -> &'static ServerConfig {
    SERVER_CONFIG.get_or_init(|| {
        let server_config_toml_str = include_str!(concat!(env!("OUT_DIR"), "/server_config.toml"));
        toml::from_str(server_config_toml_str)
            .expect("Failed to parse generated ServerConfig TOML")
    })
}
static SERVER_CONFIG: OnceLock<ServerConfig> = OnceLock::new();

/// This `main()` function is the entry point for the shared backend server.
#[cfg(feature = "server")]
fn main() {
    env_logger::Builder::from_env( // initialize server logging
        env_logger::Env::default().default_filter_or("info")
    ).init();
    dioxus::serve(|| async move {
        // override DefaultBodyLimit as needed for large file uploads
        use dioxus::fullstack::axum_core::extract::DefaultBodyLimit;
        const MAX_UPLOAD_BYTES: usize = 4 * 1024 * 1024;
        let router = dioxus::server::router(RudiServerBoundaries)
            .layer(DefaultBodyLimit::max(MAX_UPLOAD_BYTES));
        Ok(router)
    })
}

/// This `main()` function is the entry point for the client WASM.
#[cfg(not(feature = "server"))]
fn main() {
    let _ = console_log::init_with_level(log::Level::Info); // initialize console logging
    dioxus::launch(RudiServerBoundaries);
}




/// The `RudiServerBoundaries` component provides a top-level
/// `ErrorBoundary` and `SuspenseBoundary` for the apps interface.
#[component]
fn RudiServerBoundaries() -> Element {
    rsx! {
        ErrorBoundary {
            handle_error: |errors: ErrorContext| rsx! {
                div { class: "server-load-error",
                    p { "{errors:?}" }
                }
            },
            SuspenseBoundary {
                fallback: |_| rsx! {
                    div { class: "server-load-loading",
                        p { "Loading RuDI interface..." }
                    }
                },
                RudiServer {}
            }
        }
    }
}

/// The `RudiServer` component initializes the web page and router.
#[component]
fn RudiServer() -> Element {
    rsx! {
        document::Link { rel: "icon", href: asset!("/assets/favicon.ico") }
        // document::Script { src: asset!("/assets/camera.js") }
        document::Link { rel: "stylesheet", href: asset!("/assets/main.css") }
        document::Link {
            rel: "stylesheet",
            href: asset!("/assets/dx-components-theme.css"),
        }
        Router::<RudiRouter> {}
    }
}

/// Shared navbar component.
#[component]
fn RudiLayout() -> Element {
    rsx! {
        div { class: "rudi-header-layout" 
            div { class: "rudi-sidebar-layout"
                div { "Site Name" }
                div { "Header Content" }
            }
            div { class: "rudi-sidebar-layout"
                div { class: "app_steps_navbar",
                    Link { to: RudiRouter::AppStep1Component {}, "App Step 1" }
                    // add app step links as needed
                }
                Outlet::<RudiRouter> {}
            }
        }
    }
}
.rudi-header-layout {
  display: grid;
  grid-template-rows: 50px 1fr;
}
.rudi-sidebar-layout {
  display: grid;
  grid-template-columns: 150px 1fr;
}

/// Shared navbar component.
#[component]
fn App1Layout() -> Element {
    rsx! {
        div { class: "app_steps_navbar" 
            div { class: "app_steps_navbar",
                Link { to: RudiRouter::AppStep1Component {}, "App Step 1" }
                // add app step links as needed
            }
            Outlet::<RudiRouter> {}
        }
    }
}
