# REQUIRED: pipeline metadata
pipeline:
    name: demo_pipeline
    description: "a working demo that serves as a template for new pipelines"
    # version: v0.0.1 # OPTIONAL: version of this pipeline (not its suite); required if containers are used

# OPTIONAL: external suite version dependencies
# suiteVersions:
#     suiteName: v0.0.0 # use this version of a suite invoked as 'suite//module', etc. [latest]

# REQUIRED: pipeline-specific actions, called as 'rudi <pipelineName> <action> [options]'
actions: 
    # OPTIONAL: family lists in _global are prepended to every action
    _global:   
        environment: suite-demo # environment name; if omitted, use an automated, sharable name
        condaFamilies:
            - base
            - r-4.1
            - snakemake
        optionFamilies:
            - demo
    do:
        order: 1
        thread: do
        # environment: demo-do
        # condaFamilies:
        #     - base
        #     - r-4.1      
        # optionFamilies:
        #     - demo
        resources:
            required:
                total-ram: 2G
            recommended: 
                n-cpu: 1
                ram-per-cpu: 2G
        job-manager:
            recommended:
                time-limit: 1:00:00
        description: "list files in a directory, make a plot, print a table, and sleep for 15 seconds"      
    snakemake:
        order: 2
        thread: snakemake
        # environment: demo-snakemake
        # condaFamilies:
        #     - base
        #     - r-4.1     
        #     - snakemake
        optionFamilies:
        #     - demo
            - snakemake # this is a shared options module
        resources:
            required:
                total-ram: 4G
            recommended: 
                n-cpu: 2
                ram-per-cpu: 2G
        job-manager:
            recommended:
                time-limit: 1:00:00
        description: "does the same thing as 'do', but uses snakemake in Workflow.sh"

# OPTIONAL: create a data package for loading into apps
package:
    do: # the pipeline action after which a data package should assembled
        uploadType: rudi_demo # a signal to the framework regarding the package contents
        files:
            directoryContents:  # a contentFileType of any name you choose; 'manifestFile' has special meaning
                type: file-list # additional information as to the file type
                file: $DATA_FILE_PREFIX.directoryContents.txt
            dataFrame:
                type: sample-value-matrix
                header: true
                separator: comma
                file: $DATA_FILE_PREFIX.mtcars.csv
    # snakemake: 
    #     uploadType: _template
    #     extends: do # the new package will add files to the package from a previous step
    #     files: # continue as above

# OPTIONAL: enable version-controlled Singularity containers for this pipeline
container:
    supported: false    # set to true if you maintain a container registry for this pipeline [false]
    registry:  ghcr.io  # domain name of your OCI-compatible, oras-accessible, container registry [ghcr.io]
    owner:     xxxxxxxx # REQUIRED: the name of the owner, e.g., user or organization, at 'registry'
    installer: apt-get  # the installer program used by the container OS, typically apt-get or yum [apt-get]
